name: Semantic release

on:
  push:
    branches:
      - main
      - alpha
      - beta

env:
  project-directory: ./

jobs:
  release:
    name: Release and Build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
