name: Publish RRIVCTL

on:
  push:
    tags:
      - "v**"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Build binaries
        run: npm run binary
        env:
          RRIV_API_URL: https://api-dev.rriv.org/rriv
          KEYCLOAK_URL: https://auth-dev.rriv.org/realms/rriv-beta-dev/protocol/openid-connect/token
          KEYCLOAK_CLIENT_ID: rrivctl
          DATA_API_URL: https://api-dev.rriv.org/data/readings

      - name: Upload mac binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: apps/rriv-cli-macos
          asset_name: rrivcli-macos
          tag: ${{ github.ref }}
          overwrite: true
          body: "macos"

      - name: Upload linux binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: apps/rriv-cli-linux
          asset_name: rrivcli-linux
          tag: ${{ github.ref }}
          overwrite: true
          body: "linux"

      - name: Upload win binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: apps/rriv-cli-win.exe
          asset_name: rrivcli-windows.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "windows"
